"""
Domain Randomizer — NVIDIA Omniverse Replicator

Applies stochastic perturbations to an existing warehouse USD stage so that
neural networks trained on the synthetic data generalise to real facilities.

All methods accept an optional `seed` argument for reproducible episodes.

Usage:
    from isaac_sim.domain_randomizer import DomainRandomizer
    dr = DomainRandomizer(stage)
    dr.randomize_lighting(seed=42)
    dr.randomize_textures()
    dr.randomize_worker_count(min_workers=2, max_workers=8)
"""

from __future__ import annotations

import math
import random
from typing import List, Optional, Tuple

import omni.replicator.core as rep
import omni.usd
from isaacsim.core.utils.stage import get_current_stage
from pxr import Gf, Sdf, Usd, UsdGeom, UsdLux, UsdShade


# ---------------------------------------------------------------------------
# Asset library — Nucleus paths used for material / character swaps
# ---------------------------------------------------------------------------

_FLOOR_MDL_VARIANTS = [
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/ConcreteFloor_A.mdl",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/ConcreteFloor_B.mdl",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/EpoxyFloor_A.mdl",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/GratingFloor_A.mdl",
]

_WALL_MDL_VARIANTS = [
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/CinderBlock_A.mdl",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/MetalPanel_A.mdl",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/InsulatedPanel_A.mdl",
]

_RACK_MDL_VARIANTS = [
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/MetalOrange.mdl",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/MetalBlue.mdl",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/MetalGrey.mdl",
]

_WORKER_USD_PATHS = [
    "omniverse://localhost/NVIDIA/Assets/Characters/Worker_Male_A/Worker_Male_A.usd",
    "omniverse://localhost/NVIDIA/Assets/Characters/Worker_Female_A/Worker_Female_A.usd",
    "omniverse://localhost/NVIDIA/Assets/Characters/Worker_Male_B/Worker_Male_B.usd",
]

_FORKLIFT_USD_PATHS = [
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Equipment/Forklift_A.usd",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Equipment/Forklift_B.usd",
    "omniverse://localhost/NVIDIA/Assets/Warehouse/Equipment/Reach_Truck_A.usd",
]

_BOX_COLOURS: List[Tuple[float, float, float]] = [
    (0.78, 0.60, 0.35),   # cardboard brown
    (0.2, 0.4, 0.8),      # blue crate
    (0.9, 0.2, 0.2),      # red bin
    (0.3, 0.7, 0.3),      # green tote
    (0.9, 0.85, 0.1),     # yellow hazard
    (0.95, 0.95, 0.95),   # white carton
]


# ---------------------------------------------------------------------------
# DomainRandomizer
# ---------------------------------------------------------------------------

class DomainRandomizer:
    """
    Randomises every visual and semantic aspect of the warehouse stage so that
    synthetic training data covers the distribution of real-world appearances.

    Parameters
    ----------
    stage : Usd.Stage
        The live USD stage generated by WarehouseGenerator.
    warehouse_path : str
        Root prim path of the warehouse (default ``/World/Warehouse``).
    """

    WAREHOUSE_PATH = "/World/Warehouse"
    LIGHTING_PATH = "/World/Warehouse/Lighting"
    RACKS_PATH = "/World/Warehouse/Racks"
    ACTORS_PATH = "/World/Actors"

    def __init__(
        self,
        stage: Optional[Usd.Stage] = None,
        warehouse_path: str = WAREHOUSE_PATH,
    ) -> None:
        self._stage = stage or get_current_stage()
        self._warehouse_path = warehouse_path
        self._lighting_path = f"{warehouse_path}/Lighting"
        self._racks_path = f"{warehouse_path}/Racks"
        self._actors_path = "/World/Actors"
        self._ensure_actors_scope()

        # Internal state
        self._worker_prims: List[Usd.Prim] = []
        self._forklift_prims: List[Usd.Prim] = []
        self._inventory_prims: List[Usd.Prim] = []

    # ------------------------------------------------------------------
    # Lighting randomisation
    # ------------------------------------------------------------------

    def randomize_lighting(
        self,
        seed: Optional[int] = None,
        intensity_range: Tuple[float, float] = (1000.0, 8000.0),
        cct_range: Tuple[float, float] = (2700.0, 6500.0),  # Kelvin
        shadow_softness_range: Tuple[float, float] = (0.0, 10.0),
    ) -> None:
        """
        Vary every light in /Lighting — intensity, colour temperature and
        shadow softness — to simulate different times of day and fixture types.
        """
        rng = random.Random(seed)

        lighting_prim = self._stage.GetPrimAtPath(self._lighting_path)
        if not lighting_prim.IsValid():
            return

        for prim in lighting_prim.GetChildren():
            if not any(
                prim.IsA(t)
                for t in (
                    UsdLux.RectLight,
                    UsdLux.SphereLight,
                    UsdLux.DiskLight,
                    UsdLux.DistantLight,
                )
            ):
                continue

            # Intensity
            intensity = rng.uniform(*intensity_range)
            light = UsdLux.LightAPI(prim)
            light.CreateIntensityAttr(intensity)

            # Colour temperature → RGB
            rgb = self._kelvin_to_rgb(rng.uniform(*cct_range))
            light.CreateColorAttr(Gf.Vec3f(*rgb))

            # Shadow softness (only RectLight and DistantLight support it natively)
            if prim.IsA(UsdLux.RectLight):
                UsdLux.ShapingAPI.Apply(prim)
                # shadow:blur maps to softness in Kit renderer
                shadow_attr = prim.GetAttribute("inputs:shadow:blur")
                if shadow_attr:
                    shadow_attr.Set(rng.uniform(*shadow_softness_range))

        # Global environment dome (optional — only if present)
        dome_path = f"{self._lighting_path}/EnvDome"
        dome_prim = self._stage.GetPrimAtPath(dome_path)
        if dome_prim.IsValid():
            dome_light = UsdLux.DomeLight(dome_prim)
            dome_light.CreateIntensityAttr(rng.uniform(50.0, 500.0))

    @staticmethod
    def _kelvin_to_rgb(temp_k: float) -> Tuple[float, float, float]:
        """Approximate Planckian locus → sRGB (Tanner Helland algorithm)."""
        temp_k = max(1000.0, min(temp_k, 40000.0))
        t = temp_k / 100.0

        if t <= 66.0:
            r = 1.0
            g = max(0.0, min(1.0, (99.4708025861 * math.log(t) - 161.1195681661) / 255.0))
        else:
            r = max(0.0, min(1.0, (329.698727446 * (t - 60.0) ** -0.1332047592) / 255.0))
            g = max(0.0, min(1.0, (288.1221695283 * (t - 60.0) ** -0.0755148492) / 255.0))

        if t >= 66.0:
            b = 1.0
        elif t <= 19.0:
            b = 0.0
        else:
            b = max(0.0, min(1.0, (138.5177312231 * math.log(t - 10.0) - 305.0447927307) / 255.0))

        return (r, g, b)

    # ------------------------------------------------------------------
    # Texture / material randomisation
    # ------------------------------------------------------------------

    def randomize_textures(self, seed: Optional[int] = None) -> None:
        """
        Swap MDL materials on floor, walls and racks from the asset library.
        Uses omni.replicator.core material randomisation where possible,
        falls back to direct USD material rebinding.
        """
        rng = random.Random(seed)

        # ---- Floor ----
        floor_prim = self._stage.GetPrimAtPath(f"{self._warehouse_path}/Floor")
        if floor_prim.IsValid():
            mdl = rng.choice(_FLOOR_MDL_VARIANTS)
            self._rebind_mdl(floor_prim, "FloorMat_Rand", mdl)

        # ---- Walls ----
        for wall_name in ("Wall_North", "Wall_South", "Wall_East", "Wall_West"):
            wall_prim = self._stage.GetPrimAtPath(
                f"{self._warehouse_path}/{wall_name}"
            )
            if wall_prim.IsValid():
                mdl = rng.choice(_WALL_MDL_VARIANTS)
                self._rebind_mdl(wall_prim, f"{wall_name}Mat_Rand", mdl)

        # ---- Racks ----
        racks_prim = self._stage.GetPrimAtPath(self._racks_path)
        if racks_prim.IsValid():
            mdl = rng.choice(_RACK_MDL_VARIANTS)
            for rack_prim in racks_prim.GetChildren():
                self._rebind_mdl(rack_prim, "RackMat_Rand", mdl)

        # ---- Replicator material randomisation (runtime) ----
        with rep.new_layer():
            if floor_prim.IsValid():
                rep.randomizer.materials(
                    [f"{self._warehouse_path}/Floor"],
                    on=rep.trigger.on_frame(),
                )

    def _rebind_mdl(
        self, prim: Usd.Prim, mat_name: str, mdl_path: str
    ) -> None:
        """Create (or reuse) an MDL material prim and bind it to `prim`."""
        scope = "/World/Looks"
        mat_stage_path = f"{scope}/{mat_name}"

        mat_prim = self._stage.GetPrimAtPath(mat_stage_path)
        if not mat_prim.IsValid():
            material = UsdShade.Material.Define(self._stage, mat_stage_path)
            shader = UsdShade.Shader.Define(
                self._stage, f"{mat_stage_path}/Shader"
            )
            shader.CreateIdAttr("mdlMaterial")
            shader.CreateInput("module", Sdf.ValueTypeNames.Asset).Set(mdl_path)
            material.CreateSurfaceOutput("mdl").ConnectToSource(
                shader.ConnectableAPI(), "out"
            )
            mat_prim = self._stage.GetPrimAtPath(mat_stage_path)

        binding_api = UsdShade.MaterialBindingAPI(prim)
        material = UsdShade.Material(mat_prim)
        binding_api.Bind(material)

    # ------------------------------------------------------------------
    # Worker / character randomisation
    # ------------------------------------------------------------------

    def randomize_worker_count(
        self,
        seed: Optional[int] = None,
        min_workers: int = 0,
        max_workers: int = 20,
        floor_bounds: Tuple[float, float, float, float] = (5.0, 5.0, 115.0, 55.0),
    ) -> List[str]:
        """
        Remove existing worker prims then spawn between min_workers and
        max_workers animated human characters at random floor positions.

        Returns a list of USD paths for the spawned workers.
        """
        rng = random.Random(seed)
        self._clear_prims_in_scope(f"{self._actors_path}/Workers")

        count = rng.randint(min_workers, max_workers)
        x_min, y_min, x_max, y_max = floor_bounds
        spawned_paths: List[str] = []

        for i in range(count):
            asset = rng.choice(_WORKER_USD_PATHS)
            x = rng.uniform(x_min, x_max)
            y = rng.uniform(y_min, y_max)
            heading = rng.uniform(0.0, 360.0)
            path = f"{self._actors_path}/Workers/Worker_{i:04d}"

            from isaacsim.core.utils.stage import add_reference_to_stage
            ref_prim = add_reference_to_stage(usd_path=asset, prim_path=path)
            prim = self._stage.GetPrimAtPath(path)
            if prim.IsValid():
                xf = UsdGeom.Xformable(prim)
                xf.AddTranslateOp().Set(Gf.Vec3d(x, y, 0.0))
                xf.AddRotateZOp().Set(heading)
                self._worker_prims.append(prim)
                spawned_paths.append(path)

        return spawned_paths

    # ------------------------------------------------------------------
    # Forklift randomisation
    # ------------------------------------------------------------------

    def randomize_forklift_count(
        self,
        seed: Optional[int] = None,
        min_forklifts: int = 0,
        max_forklifts: int = 10,
        floor_bounds: Tuple[float, float, float, float] = (5.0, 5.0, 115.0, 55.0),
    ) -> List[str]:
        """Spawn between min_forklifts and max_forklifts forklift USDs."""
        rng = random.Random(seed)
        self._clear_prims_in_scope(f"{self._actors_path}/Forklifts")

        count = rng.randint(min_forklifts, max_forklifts)
        x_min, y_min, x_max, y_max = floor_bounds
        spawned_paths: List[str] = []

        for i in range(count):
            asset = rng.choice(_FORKLIFT_USD_PATHS)
            x = rng.uniform(x_min, x_max)
            y = rng.uniform(y_min, y_max)
            heading = rng.uniform(0.0, 360.0)
            path = f"{self._actors_path}/Forklifts/Forklift_{i:04d}"

            from isaacsim.core.utils.stage import add_reference_to_stage
            ref_prim = add_reference_to_stage(usd_path=asset, prim_path=path)
            prim = self._stage.GetPrimAtPath(path)
            if prim.IsValid():
                xf = UsdGeom.Xformable(prim)
                xf.AddTranslateOp().Set(Gf.Vec3d(x, y, 0.0))
                xf.AddRotateZOp().Set(heading)
                self._forklift_prims.append(prim)
                spawned_paths.append(path)

        return spawned_paths

    # ------------------------------------------------------------------
    # Inventory randomisation
    # ------------------------------------------------------------------

    def randomize_inventory(
        self,
        seed: Optional[int] = None,
        fill_ratio: float = 0.7,
        box_size_range: Tuple[Tuple[float, float], ...] = (
            (0.2, 0.6),  # half-extents X
            (0.2, 0.6),  # half-extents Y
            (0.15, 0.5), # half-extents Z
        ),
    ) -> int:
        """
        Fill rack beam levels with box prims. Each box gets a randomised
        colour from _BOX_COLOURS and a randomised size within box_size_range.

        Returns the total number of boxes placed.
        """
        rng = random.Random(seed)
        racks_prim = self._stage.GetPrimAtPath(self._racks_path)
        if not racks_prim.IsValid():
            return 0

        self._clear_prims_in_scope(f"{self._actors_path}/Inventory")
        inv_scope = f"{self._actors_path}/Inventory"
        self._ensure_scope(inv_scope)

        box_count = 0
        for rack_prim in racks_prim.GetChildren():
            rack_path = str(rack_prim.GetPath())
            # Collect beam level Z positions (rough heuristic from Upright height)
            beam_levels = self._estimate_beam_levels(rack_prim)
            rack_xform = self._get_world_translate(rack_prim)

            for level_z in beam_levels:
                if rng.random() > fill_ratio:
                    continue
                # Place 1-3 boxes per level per bay
                for b in range(rng.randint(1, 3)):
                    if rng.random() > fill_ratio:
                        continue
                    bx = rng.uniform(*box_size_range[0])
                    by = rng.uniform(*box_size_range[1])
                    bz = rng.uniform(*box_size_range[2])
                    colour = rng.choice(_BOX_COLOURS)

                    box_path = f"{inv_scope}/Box_{box_count:06d}"
                    cube = UsdGeom.Cube.Define(self._stage, box_path)
                    prim = self._stage.GetPrimAtPath(box_path)
                    xf = UsdGeom.Xformable(prim)
                    xf.AddTranslateOp().Set(
                        Gf.Vec3d(
                            rack_xform[0] + rng.uniform(-0.5, 0.5),
                            rack_xform[1] + rng.uniform(-0.3, 0.3),
                            level_z + bz,
                        )
                    )
                    xf.AddScaleOp().Set(Gf.Vec3f(bx, by, bz))

                    # Colour via display colour
                    UsdGeom.Gprim(prim).CreateDisplayColorAttr(
                        [Gf.Vec3f(*colour)]
                    )
                    box_count += 1

        return box_count

    def _estimate_beam_levels(self, rack_prim: Usd.Prim) -> List[float]:
        """Return approximate Z heights of beam levels for a rack prim."""
        # If real asset: inspect children named Beam_*
        levels: List[float] = []
        for child in rack_prim.GetChildren():
            name = child.GetName()
            if "Beam" in name or "Level" in name:
                t = child.GetAttribute("xformOp:translate")
                if t:
                    val = t.Get()
                    if val:
                        levels.append(float(val[2]))
        if not levels:
            # Fallback: evenly spaced levels
            levels = [1.0 + i * 1.2 for i in range(4)]
        return sorted(levels)

    def _get_world_translate(self, prim: Usd.Prim) -> Tuple[float, float, float]:
        t_attr = prim.GetAttribute("xformOp:translate")
        if t_attr:
            val = t_attr.Get()
            if val:
                return (float(val[0]), float(val[1]), float(val[2]))
        return (0.0, 0.0, 0.0)

    # ------------------------------------------------------------------
    # Time of day
    # ------------------------------------------------------------------

    def randomize_time_of_day(
        self,
        seed: Optional[int] = None,
        hour_range: Tuple[float, float] = (5.0, 21.0),
    ) -> float:
        """
        Adjust sun elevation and intensity to simulate a random hour.

        Returns the chosen hour (float, 0-24).
        """
        rng = random.Random(seed)
        hour = rng.uniform(*hour_range)

        # Sun elevation angle: peaks at noon, zero at horizon
        elevation = max(0.0, 90.0 * math.sin(math.pi * (hour - 6.0) / 12.0))
        azimuth = 180.0 + (hour - 12.0) * 15.0  # 15°/hr

        sun_prim = self._stage.GetPrimAtPath(f"{self._lighting_path}/Sun")
        if sun_prim.IsValid():
            xf = UsdGeom.Xformable(sun_prim)
            # Clear existing rotation ops and set new values
            ops = xf.GetOrderedXformOps()
            for op in ops:
                if op.GetOpType() == UsdGeom.XformOp.TypeRotateXYZ:
                    op.Set(Gf.Vec3f(elevation, 0.0, azimuth))
                    break
            else:
                xf.AddRotateXYZOp().Set(Gf.Vec3f(elevation, 0.0, azimuth))

            sun_light = UsdLux.DistantLight(sun_prim)
            intensity = max(0.0, 1500.0 * math.sin(math.pi * (hour - 6.0) / 12.0))
            sun_light.CreateIntensityAttr(intensity)

        return hour

    # ------------------------------------------------------------------
    # Weather effects
    # ------------------------------------------------------------------

    def randomize_weather(
        self,
        seed: Optional[int] = None,
        weather_types: Tuple[str, ...] = ("clear", "dusty", "foggy", "wet"),
    ) -> str:
        """
        Simulate environmental conditions using Replicator particle / fog nodes.

        Returns the selected weather type.
        """
        rng = random.Random(seed)
        weather = rng.choice(weather_types)

        with rep.new_layer():
            if weather == "dusty":
                self._apply_dust_particles(rng)
            elif weather == "foggy":
                self._apply_fog(rng)
            elif weather == "wet":
                self._apply_wet_floor(rng)
            # "clear" — no additional FX

        return weather

    def _apply_dust_particles(self, rng: random.Random) -> None:
        """Spawn floating dust particle system via Replicator."""
        with rep.new_layer():
            particles = rep.create.particles(
                position=(60.0, 30.0, 4.5),
                spread=(55.0, 25.0, 2.0),
                count=rng.randint(500, 2000),
                size=rng.uniform(0.005, 0.02),
                color=(0.85, 0.75, 0.55, 0.3),   # RGBA
                velocity=(rng.uniform(-0.2, 0.2), rng.uniform(-0.1, 0.1), 0.0),
                lifetime=rng.uniform(5.0, 15.0),
            )

    def _apply_fog(self, rng: random.Random) -> None:
        """Set scene-level exponential height fog parameters."""
        # omni.kit.commands provides scene settings API
        try:
            import omni.kit.commands
            omni.kit.commands.execute(
                "SetFogSettings",
                density=rng.uniform(0.01, 0.08),
                height_falloff=rng.uniform(0.1, 0.5),
                fog_color=(0.8, 0.8, 0.82),
                enable=True,
            )
        except Exception:
            # Fallback: create a volumetric cube proxy
            fog_path = f"{self._warehouse_path}/Fog"
            if not self._stage.GetPrimAtPath(fog_path).IsValid():
                UsdGeom.Cube.Define(self._stage, fog_path)
            prim = self._stage.GetPrimAtPath(fog_path)
            UsdGeom.Xformable(prim).AddTranslateOp().Set(Gf.Vec3d(60, 30, 4.5))
            UsdGeom.Xformable(prim).AddScaleOp().Set(
                Gf.Vec3f(60, 30, rng.uniform(1.0, 5.0))
            )

    def _apply_wet_floor(self, rng: random.Random) -> None:
        """Make floor material appear wet by swapping to a wet MDL variant."""
        wet_mdl = (
            "omniverse://localhost/NVIDIA/Assets/Warehouse/Materials/"
            "ConcreteFloor_Wet.mdl"
        )
        floor_prim = self._stage.GetPrimAtPath(f"{self._warehouse_path}/Floor")
        if floor_prim.IsValid():
            self._rebind_mdl(floor_prim, "WetFloorMat", wet_mdl)

        # Add puddle decals
        puddle_count = rng.randint(3, 12)
        for i in range(puddle_count):
            puddle_path = f"{self._warehouse_path}/Puddle_{i:02d}"
            if not self._stage.GetPrimAtPath(puddle_path).IsValid():
                UsdGeom.Plane.Define(self._stage, puddle_path)
            prim = self._stage.GetPrimAtPath(puddle_path)
            xf = UsdGeom.Xformable(prim)
            xf.AddTranslateOp().Set(
                Gf.Vec3d(
                    rng.uniform(5.0, 115.0),
                    rng.uniform(5.0, 55.0),
                    0.002,
                )
            )
            xf.AddScaleOp().Set(
                Gf.Vec3f(rng.uniform(0.3, 1.5), rng.uniform(0.3, 1.5), 1.0)
            )

    # ------------------------------------------------------------------
    # Internal helpers
    # ------------------------------------------------------------------

    def _ensure_actors_scope(self) -> None:
        self._ensure_scope(self._actors_path)
        self._ensure_scope(f"{self._actors_path}/Workers")
        self._ensure_scope(f"{self._actors_path}/Forklifts")

    def _ensure_scope(self, path: str) -> None:
        prim = self._stage.GetPrimAtPath(path)
        if not prim.IsValid():
            UsdGeom.Scope.Define(self._stage, path)

    def _clear_prims_in_scope(self, scope_path: str) -> None:
        """Delete all children of a scope prim."""
        scope_prim = self._stage.GetPrimAtPath(scope_path)
        if not scope_prim.IsValid():
            self._ensure_scope(scope_path)
            return
        for child in list(scope_prim.GetChildren()):
            self._stage.RemovePrim(child.GetPath())
